// Icons are from Lucide React — https://lucide.dev/icons
// Valid icon values for the `icon` field in JSON:
// user, bot, server, database, zap, plug, git-branch, globe, brain, settings,
// folder, cloud, mail, lock, key, search, star, rocket, lightbulb, flame,
// check-circle, map-pin, trophy, message, phone, wrench, chart, eye, music,
// heart, flag, shield, flask, trending, paint, sparkles, smile, home, building,
// briefcase, graduate, gift, clock, calendar, file, cog, cpu, link, code,
// terminal, package, layers, bell, alert, info, help, refresh, share, download,
// upload, image, video, mic, headphones, camera, monitor, wifi, card, cart,
// dollar, pie, activity, target, crosshair, compass, map, bookmark, tag, hash,
// at, send

import {
  User, Bot, Server, Database, Zap, Plug, GitBranch, Globe,
  Brain, Settings, Folder, Cloud, Mail, Lock, Key, Search,
  Star, Rocket, Lightbulb, Flame, CheckCircle, MapPin, Trophy,
  MessageCircle, Smartphone, Wrench, BarChart2, Eye, Music, Heart,
  Flag, Shield, FlaskConical, TrendingUp, Paintbrush, Sparkles, Smile,
  Home, Building2, Briefcase, GraduationCap, Gift, Clock, Calendar,
  FileText, Cog, Cpu, Link, Code, Terminal, Package, Layers,
  Bell, AlertCircle, Info, HelpCircle, RefreshCw, Share2, Download,
  Upload, Image, Video, Mic, Headphones, Camera, Monitor, Wifi,
  CreditCard, ShoppingCart, DollarSign, PieChart, Activity, Target,
  Crosshair, Compass, Map, Bookmark, Tag, Hash, AtSign, Send,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export interface IconEntry { name: string; label: string; Icon: LucideIcon }

export const NODE_ICONS: IconEntry[] = [
  { name: 'user', label: 'user', Icon: User },
  { name: 'bot', label: 'bot', Icon: Bot },
  { name: 'server', label: 'server', Icon: Server },
  { name: 'database', label: 'database', Icon: Database },
  { name: 'zap', label: 'zap', Icon: Zap },
  { name: 'plug', label: 'plug', Icon: Plug },
  { name: 'git-branch', label: 'git-branch', Icon: GitBranch },
  { name: 'globe', label: 'globe', Icon: Globe },
  { name: 'brain', label: 'brain', Icon: Brain },
  { name: 'settings', label: 'settings', Icon: Settings },
  { name: 'folder', label: 'folder', Icon: Folder },
  { name: 'cloud', label: 'cloud', Icon: Cloud },
  { name: 'mail', label: 'mail', Icon: Mail },
  { name: 'lock', label: 'lock', Icon: Lock },
  { name: 'key', label: 'key', Icon: Key },
  { name: 'search', label: 'search', Icon: Search },
  { name: 'star', label: 'star', Icon: Star },
  { name: 'rocket', label: 'rocket', Icon: Rocket },
  { name: 'lightbulb', label: 'lightbulb', Icon: Lightbulb },
  { name: 'flame', label: 'flame', Icon: Flame },
  { name: 'check-circle', label: 'check', Icon: CheckCircle },
  { name: 'map-pin', label: 'map-pin', Icon: MapPin },
  { name: 'trophy', label: 'trophy', Icon: Trophy },
  { name: 'message', label: 'message', Icon: MessageCircle },
  { name: 'phone', label: 'phone', Icon: Smartphone },
  { name: 'wrench', label: 'wrench', Icon: Wrench },
  { name: 'chart', label: 'chart', Icon: BarChart2 },
  { name: 'eye', label: 'eye', Icon: Eye },
  { name: 'music', label: 'music', Icon: Music },
  { name: 'heart', label: 'heart', Icon: Heart },
  { name: 'flag', label: 'flag', Icon: Flag },
  { name: 'shield', label: 'shield', Icon: Shield },
  { name: 'flask', label: 'flask', Icon: FlaskConical },
  { name: 'trending', label: 'trending', Icon: TrendingUp },
  { name: 'paint', label: 'paint', Icon: Paintbrush },
  { name: 'sparkles', label: 'sparkles', Icon: Sparkles },
  { name: 'smile', label: 'smile', Icon: Smile },
  { name: 'home', label: 'home', Icon: Home },
  { name: 'building', label: 'building', Icon: Building2 },
  { name: 'briefcase', label: 'briefcase', Icon: Briefcase },
  { name: 'graduate', label: 'graduate', Icon: GraduationCap },
  { name: 'gift', label: 'gift', Icon: Gift },
  { name: 'clock', label: 'clock', Icon: Clock },
  { name: 'calendar', label: 'calendar', Icon: Calendar },
  { name: 'file', label: 'file', Icon: FileText },
  { name: 'cog', label: 'cog', Icon: Cog },
  { name: 'cpu', label: 'cpu', Icon: Cpu },
  { name: 'link', label: 'link', Icon: Link },
  { name: 'code', label: 'code', Icon: Code },
  { name: 'terminal', label: 'terminal', Icon: Terminal },
  { name: 'package', label: 'package', Icon: Package },
  { name: 'layers', label: 'layers', Icon: Layers },
  { name: 'bell', label: 'bell', Icon: Bell },
  { name: 'alert', label: 'alert', Icon: AlertCircle },
  { name: 'info', label: 'info', Icon: Info },
  { name: 'help', label: 'help', Icon: HelpCircle },
  { name: 'refresh', label: 'refresh', Icon: RefreshCw },
  { name: 'share', label: 'share', Icon: Share2 },
  { name: 'download', label: 'download', Icon: Download },
  { name: 'upload', label: 'upload', Icon: Upload },
  { name: 'image', label: 'image', Icon: Image },
  { name: 'video', label: 'video', Icon: Video },
  { name: 'mic', label: 'mic', Icon: Mic },
  { name: 'headphones', label: 'headphones', Icon: Headphones },
  { name: 'camera', label: 'camera', Icon: Camera },
  { name: 'monitor', label: 'monitor', Icon: Monitor },
  { name: 'wifi', label: 'wifi', Icon: Wifi },
  { name: 'card', label: 'card', Icon: CreditCard },
  { name: 'cart', label: 'cart', Icon: ShoppingCart },
  { name: 'dollar', label: 'dollar', Icon: DollarSign },
  { name: 'pie', label: 'pie', Icon: PieChart },
  { name: 'activity', label: 'activity', Icon: Activity },
  { name: 'target', label: 'target', Icon: Target },
  { name: 'crosshair', label: 'crosshair', Icon: Crosshair },
  { name: 'compass', label: 'compass', Icon: Compass },
  { name: 'map', label: 'map', Icon: Map },
  { name: 'bookmark', label: 'bookmark', Icon: Bookmark },
  { name: 'tag', label: 'tag', Icon: Tag },
  { name: 'hash', label: 'hash', Icon: Hash },
  { name: 'at', label: 'at', Icon: AtSign },
  { name: 'send', label: 'send', Icon: Send },
]

export const ICON_MAP = Object.fromEntries(NODE_ICONS.map(e => [e.name, e.Icon]))
